CREATE TABLE catalogue_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	description varchar(255) not null,
	image_url varchar(255) not null
);

create sequence catalogue_item_id_sequence start with 1 increment by 1;

INSERT INTO catalogue_item (name,description,image_url) VALUES ( 'Friendly Kitten','Your best pal', 'https://placekitten.com/200/200' );
INSERT INTO catalogue_item (name,description,image_url) VALUES ( 'Naughty Kitten', 'Likely to tear up your curtains', 'https://placekitten.com/150/150' );
INSERT INTO catalogue_item (name,description,image_url) VALUES ( 'Adorable Kitten', 'Melt your heart', 'https://placekitten.com/250/250' );
INSERT INTO catalogue_item (name,description,image_url) VALUES ( 'Ambivalent Kitten', 'Could not care less', 'https://placekitten.com/100/100' );